/* AntB's Fork - Defines > powder.h */

#define SEC 77  // SEC = Simon Element Count, set it the same as the last element in the source.

#define PT_MUPT SEC+1
#define PT_BAGL SEC+2
#define PT_MUNE SEC+3
#define PT_RBRI SEC+4
#define PT_LH2  SEC+5
#define PT_H2   SEC+6
#define PT_H2O2 SEC+7
#define PT_SUWR SEC+8
#define PT_RADI SEC+9
#define PT_RADO SEC+10
#define PT_GROW SEC+11
#define PT_LEAD SEC+12

#define PT_RNEO SEC+13
#define PT_GNEO SEC+14
#define PT_BNEO SEC+15
#define PT_CNEO SEC+16
#define PT_MNEO SEC+17
#define PT_YNEO SEC+18

#define PT_LLED SEC+19
#define PT_VIRU SEC+20
#define PT_ZINC SEC+21
#define PT_GSTL SEC+22
#define PT_ERTH SEC+23
#define PT_SOIL SEC+24
#define PT_DBTY SEC+25
#define PT_RBTY SEC+26 

#define PT_NUM  SEC+27


