/* AntB's Fork - Defines > powder.h */

#define BEC 130  // BEC = Base Element Count, set it the same as the last element in the source.

#define PT_MUPT BEC+1
#define PT_BAGL BEC+2
#define PT_MUNE BEC+3
#define PT_RBRI BEC+4
#define PT_LH2  BEC+5
#define PT_H2   BEC+6
#define PT_H2O2 BEC+7
#define PT_SUWR BEC+8
#define PT_RADI BEC+9
#define PT_RADO BEC+10
#define PT_GROW BEC+11
#define PT_LEAD BEC+12

#define PT_RNEO BEC+13
#define PT_GNEO BEC+14
#define PT_BNEO BEC+15
#define PT_CNEO BEC+16
#define PT_MNEO BEC+17
#define PT_YNEO BEC+18

#define PT_LLED BEC+19
#define PT_VIRU BEC+20
#define PT_ZINC BEC+21
#define PT_GSTL BEC+22
#define PT_ERTH BEC+23
#define PT_SOIL BEC+24
#define PT_DBTY BEC+25
#define PT_SBTY BEC+26 
#define PT_NP2  BEC+27
#define PT_EMIT BEC+28
#define PT_FART BEC+29

#define PT_NUM  BEC+30


