/* AntB's Fork - Element States > powder.h */

/* MuPt */ {ST_GAS,     PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Bagl */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* MuNe */ {ST_GAS,     PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* RBRI */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 2273.0f, PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* LH2  */ {ST_LIQUID,  PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_H2,   20.0f,   PT_NONE, 0.0f},
/* H2   */ {ST_GAS,     PT_NONE, 0.0f,    PT_LH2,  10.0f,   PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* H2O2 */ {ST_LIQUID,  PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f}, 
/* SUWr */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 1687.0f, PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Radi */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Rado */ {ST_GAS,     PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Grow */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Lead */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LLED, 700.6f,  PT_NONE, 0.0f,    PT_NONE, 0.0f},

//Neons
/* R    */ {ST_GAS,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* G    */ {ST_GAS,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* B    */ {ST_GAS,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* C    */ {ST_GAS,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* M    */ {ST_GAS,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Y    */ {ST_GAS,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
//End Neons

/* LLed */ {ST_LIQUID,  PT_LEAD, 600.6f,  PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* X    */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Zinc */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 1000.0f, PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* GStl */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 2000.0f, PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Erth */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 500.0f,  PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Soil */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 500.0f,  PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* DBty */ {ST_SOLID,	PT_NONE, 0.0f,	  PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_PLSM, 2273.0f},
/* RBty */ {ST_SOLID,	PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_PLSM, 2273.0f},
/* NP2  */ {ST_LIQUID,  PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Emit */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Fart */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Clou */ {ST_GAS,     PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},

/* GOL  */ {ST_NONE,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* GOL  */ {ST_NONE,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},

/* REMX */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},

/* GOL  */ {ST_NONE,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
