/* AntB's Fork - Element States > powder.h */

/* MuPt */ {ST_GAS,     PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Bagl */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* MuNe */ {ST_GAS,     PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* RBRI */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 2273.0f, PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* LH2  */ {ST_LIQUID,  PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_H2,   20.0f,   PT_NONE, 0.0f},
/* H2   */ {ST_GAS,     PT_NONE, 0.0f,    PT_LH2,  10.0f,   PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* H2O2 */ {ST_LIQUID,  PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f}, 
/* SUWr */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LAVA, 1687.0f, PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Radi */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Rado */ {ST_GAS,     PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Grow */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Lead */ {ST_SOLID,   PT_NONE, 0.0f,    PT_LLED, 600.61f, PT_NONE, 0.0f,    PT_NONE, 0.0f},

//Neons
/* R    */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* G    */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* B    */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* C    */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* M    */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* Y    */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
//End Neons

/* LLed */ {ST_SOLID,   PT_LEAD, 600.60f, PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
/* XXXX */ {ST_SOLID,   PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f,    PT_NONE, 0.0f},
