/* AntB's Fork - Defines > powder.h */

#define PT_MUPT 76
#define PT_BAGL 77
#define PT_MUNE 78
#define PT_RBRI 79
#define PT_EMIT 80
#define PT_LH2  81
#define PT_H2   82
#define PT_H2O2 83
#define PT_SUWR 84
#define PT_RADI 85
#define PT_RADO 86
#define PT_GROW 87
#define PT_LEAD 88
#define PT_RNEO 89
#define PT_GNEO 90
#define PT_BNEO 91
#define PT_CNEO 92
#define PT_MNEO 93
#define PT_YNEO 94
#define PT_IRON 95

#define PT_NUM  96
